steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
    
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push

  - name: 'gcr.io/cloud-builders/composer'
    args: ['install', '--no-dev']

  - name: 'gcr.io/cloud-builders/php'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        php artisan key:generate

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

  - name: 'gcr.io/google-appengine/exec-wrapper'
    entrypoint: 'bash'
    args:
      - -c
      - |
        /buildstep/execute.sh \
        -i $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
        -e DB_CONNECTION=$_DB_CONNECTION \
        -e DB_SOCKET=$$DB_HOST \
        -e DB_HOST=$$DB_HOST \
        -e CLOUD_SQL_CONNECTION_NAME=$_INSTANCE_CONNECTION_NAME \
        -e DB_DATABASE=$$DB_DATABASE \
        -e DB_USERNAME=$$DB_USERNAME \
        -e DB_PASSWORD=$$DB_PASSWORD 
        -s $_INSTANCE_CONNECTION_NAME \
        -- php /app/artisan migrate --force
    waitFor:
      - Build
      - Push
      - Deploy
    id: Migrate

  images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  options:
    substitutionOption: ALLOW_LOOSE